name: Always Pass

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  always-pass:
    name: always-pass
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo "âœ… This check always passes" && exit 0
